apiVersion: skaffold/v4beta3
kind: Congif
manifests:
  rawYaml:
  - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: sreekanthlakka/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
  - image: sreekanthlakka/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.js*'
        dest: .
  - image: sreekanthlakka/tickets
    context: tickets
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
  - image: sreekanthlakka/orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
  - image: sreekanthlakka/expiration
    context: expiration
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
  - image: sreekanthlakka/payments
    context: payments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
